version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks: 
      - ew_net

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    working_dir: /var/www/html  
    volumes:
      - wpdata:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks: 
      - ew_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - ew_net


volumes:
  db_data:
    driver: local
    driver_opts:
        type: none
        device: C:\Users\elena\OneDrive\Documents\Web_page_3\db_data
        o: bind
  wpdata:
    driver: local
    driver_opts:
        type: none
        device: C:\Users\elena\OneDrive\Documents\Web_page_3\wp-content
        o: bind

networks: 
  ew_net:
    driver: bridge